

@startuml


skinparam monochrome false
skinparam shadowing false

frame Race as "Race" #LightYellow {

    folder comPocket as "comPocket" #WhiteSmoke;line:IndianRed; {
        class PostmanPocketRace <<medium>>
        class DispatcherPocketRace <<active>> <<medium>> 
        class ProtocolPocketRace <<medium>>
        class ProxyPilot <<medium>>
    }

    folder motorRace as "motorRace" #WhiteSmoke;line:IndianRed; {
        class Robot <<active>>
        class Motors
    }

    folder sensorManager as "sensorManager" #WhiteSmoke;line:IndianRed;{
        class Accelerometer <<boundary>>
        class ContactSensor <<boundary>>
        class Sensors
    }

}

DispatcherPocketRace --> PostmanPocketRace
ProxyPilot --> PostmanPocketRace
ProxyPilot --> ProtocolPocketRace
DispatcherPocketRace --> ProtocolPocketRace

Robot --> ProxyPilot
Robot --> Motors
Sensors --> Accelerometer
Sensors --> ContactSensor

Robot -l-> Sensors

DispatcherPocketRace -> Robot




@enduml
