

@startuml



skinparam monochrome false
skinparam shadowing false



node MPRemote as MPRemote
node A7Remote as A7Remote
node A7Robot as A7Robot
node M4Robot as M4Robot
node Motors as Motors 


node MPRemote as "MPRemote" #LightYellow {

    node A7Remote as "Cortex-A7" #WhiteSmoke {

        component Remote{

        }
    }
}



node MPRobot as "MPRobot" #LightYellow {

    node M4Robot as "Cortex-M4" #WhiteSmoke {
        component Race{
            
        }
    }

    node A7Robot as "Cortex-A7" #WhiteSmoke{

        component Pocket{
           
        }
    }

}


A7Remote -0- A7Robot : Protocole TCP/IP
M4Robot -0- A7Robot : Communication intercoeur
Motors -0- M4Robot : Signal modulation d'impulsion




@enduml

