

@startuml mapper
[*] --> Idle

Idle -> Scanning : start_mapper() / \n mapper_run();

Scanning -> Scanning : /mapper_file_acquisition();
Scanning -> SetLidarData : E_SET_LIDAR_DATA / \n setLidarData();
SetLidarData --> Scanning 
Scanning --> Death : E_STOP_MAPPER / \n stop_mapper();

Death --> [*]

@enduml

