

@startuml mapper

[*] --> Idle : / start_mapper();

Idle -> Scanning : E_START_MAPPER / \n mapper_run();

Scanning -> Scanning : E_SCANNING / \n file_acquisition() \n sendEvent_SetLIDARData();
Scanning -> SetLidarData : E_SET_LIDAR_DATA / \n setLidarData();
SetLidarData --> Scanning : E_ACK_LIDAR_DATA / \n sendEvent_Scanning();
Scanning --> Death : E_STOP_MAPPER / \n stop_mapper();

Death --> [*]

@enduml

